version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend/app:/code  # Sync your source code
  #     - type: tmpfs      # Temporary in-memory storage for __pycache__
  #       target: /code/__pycache__
  #   # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - app-network

networks:
  app-network:
volumes:
  mongo-data:
